services:
  web:
    build: .
    container_name: fplgeek-web
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=fplgeek.xyz,www.fplgeek.xyz
      - LETSENCRYPT_HOST=fplgeek.xyz,www.fplgeek.xyz
      - LETSENCRYPT_EMAIL=your@email.com
    depends_on:
      - server
    networks:
      - proxy

  server:
    build: ./functions
    container_name: fplgeek-server
    restart: always
    env_file: .env
    environment:
      - PORT=3000
    volumes:
      - ./public/data:/app/public/data
    expose:
      - "3000"
    networks:
      - proxy

networks:
  proxy:
    external: true